### ISSUE TITLE
>After choosing an area for drag and drop,  not all objects in the defined area are moving along as I drag it.
                    
                    >userAgent: Mozilla/5.0 (Windows NT 10.0; Win64;

### ISSUE THREAD

**Issue by usamshen** [boardx/BoardX-Community#340]
>After choosing an area for drag and drop,  not all objects in the defined area are moving along as I drag it.
                    
                    >userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36
                    email: undefined
                    username: romer.benitez

**Comment by zhangsgithub04** [comment]
If not just sticky notes, such as link icons? How about other widget object types?
