### ISSUE TITLE
>Board does not stay current with other person's changes/updates in real time. Need to refresh the browser to see their changes. Using Edge browser.
                    
                    >userAgent

### ISSUE THREAD

**Issue by boardxsupport** [boardx/BoardX-Community#360]
>Board does not stay current with other person's changes/updates in real time. Need to refresh the browser to see their changes. Using Edge browser.
                    
                    >userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36 Edg/122.0.0.0
                    email: mptaylor@live.com
                    username: mptaylor

**Comment by usamshen2** [comment]
Hi Mike, thanks for sharing the hug! is there a way for you to reproduce the bug?

Usam

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: boardxsupport ***@***.***>
Sent: Thursday, March 21, 2024 11:01:50 AM
To: boardx/BoardX-Community ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [boardx/BoardX-Community] >Board does not stay current with other person's changes/updates in real time. Need to refresh the browser to see their changes. Using Edge browser. >userAgent (Issue #360)


Board does not stay current with other person's changes/updates in real time. Need to refresh the browser to see their changes. Using Edge browser.

                >userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36 Edg/122.0.0.0
                email: ***@***.***
                username: mptaylor
