### ISSUE TITLE
>There is a display error in the numbering of the list. In the uploaded pic, the item that is supposed to be labeled "10" is mislabeled as "0". This shows a problem with the list where numbers beyond 

### ISSUE THREAD

**Issue by boardxsupport** [boardx/BoardX-Community#365]
>There is a display error in the numbering of the list. In the uploaded pic, the item that is supposed to be labeled "10" is mislabeled as "0". This shows a problem with the list where numbers beyond 10 are not displayed correctly. After the number 10, the numbers 11, 12, 13, etc., appear to be missing the first digit and are incorrectly displayed as 1, 2, 3, and so on.

                    ![numbers won't show right.jpg](https://files.boardx.us/beBT5B83vbXnsw7R5/anu9hwaYKucGwPAX3/S9ystBxYTEpKYgSSE/images/smallPic/9LggfAvxq26osmjf.jpg)
                    >userAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36
                    email: kfbldan@gmail.com
                    username: xiaodanzhang

**Comment by usamshen** [comment]
solved and pushed to develop server, please test and confirm. @Annuo820
