### ISSUE TITLE
>这个截图中，注意看Time 的地方。
有的时候，是按照每毫秒的形式来增加时间的。有时候不会显示每一毫秒的变化，可能会是5毫秒，或就不展示时间的变化了。如果刷新页面的话，会显示时间已经增加了
                    ![QQ20240409-104129@2x.png](https://files.boardx.us/beBT5B83vbXnsw7R5/P7LsMHdYhqJp8A

### ISSUE THREAD

**Issue by boardxsupport** [boardx/BoardX-Community#367]
>这个截图中，注意看Time 的地方。
有的时候，是按照每毫秒的形式来增加时间的。有时候不会显示每一毫秒的变化，可能会是5毫秒，或就不展示时间的变化了。如果刷新页面的话，会显示时间已经增加了
                    ![QQ20240409-104129@2x.png](https://files.boardx.us/beBT5B83vbXnsw7R5/P7LsMHdYhqJp8AABQ/TzEiN9aSSWZ5Jq2BG/images/smallPic/sa8MEppzr1c2ntvs.png)
                    >userAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36
                    email: kfbldan@gmail.com
                    username: xiaodanzhang

**Comment by zivonx** [comment]
@Annuo820 @usamshen  这个处理了
