### ISSUE TITLE
>When sending the outputs to email, it lost all the formats, as shown in the pic.
                    ![QQ20240409-170533@2x.png](https://files.boardx.us/beBT5B83vbXnsw7R5/P7LsMHdYhqJp8AABQ/TzEiN9aSSW

### ISSUE THREAD

**Issue by boardxsupport** [boardx/BoardX-Community#368]
>When sending the outputs to email, it lost all the formats, as shown in the pic.
                    ![QQ20240409-170533@2x.png](https://files.boardx.us/beBT5B83vbXnsw7R5/P7LsMHdYhqJp8AABQ/TzEiN9aSSWZ5Jq2BG/images/smallPic/sqqG5na1uaquyhcn.png)
                    >userAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36
                    email: kfbldan@gmail.com
                    username: xiaodanzhang

**Comment by Annuo820** [comment]
<img width="1252" alt="QQ20240409-170845@2x" src="https://github.com/boardx/BoardX-Community/assets/165532509/f0ffae4c-1acb-40b6-93ff-be7b5dd9ecfe">

**Comment by Annuo820** [comment]
See how it looks like in the email as above
