### ISSUE TITLE
>On Dark mode, the pen point is not shown well
                    ![QQ20240409-171413@2x.png](https://files.boardx.us/beBT5B83vbXnsw7R5/P7LsMHdYhqJp8AABQ/TzEiN9aSSWZ5Jq2BG/images/smallPic/38KJO6rf88b

### ISSUE THREAD

**Issue by boardxsupport** [boardx/BoardX-Community#369]
>On Dark mode, the pen point is not shown well
                    ![QQ20240409-171413@2x.png](https://files.boardx.us/beBT5B83vbXnsw7R5/P7LsMHdYhqJp8AABQ/TzEiN9aSSWZ5Jq2BG/images/smallPic/38KJO6rf88bgccyy.png)
                    >userAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36
                    email: kfbldan@gmail.com
                    username: xiaodanzhang

**Comment by usamshen** [comment]
change the default color to gray not black.
